### ISSUE TITLE
On creating a job, samples are not being recorded

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#131]
Client is attempting to submit a job. It fails on the VM with the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 184, in run
    self.func(working_directory, self.payload)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 101, in run_workflow
    workflow.run(payload.cwl_file_url, payload.workflow_object_name, payload.job_order)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlworkflow.py", line 153, in run
    raise JobStepFailed(error_message, process.output)
JobStepFailed: 'CWL workflow failed with exit code: 1\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,037 MainThread INFO toil.lib.bioio: Root logger is at level \'DEBUG\', \'toil\' logger at level \'DEBUG\'.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,039 MainThread INFO toil.lib.bioio: Logging to file \'cwltoil.log\'.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,039 MainThread INFO toil.lib.bioio: Root logger is at level \'DEBUG\', \'toil\' logger at level \'DEBUG\'.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,039 MainThread INFO toil.lib.bioio: Logging to file \'cwltoil.log\'.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,046 MainThread DEBUG toil.jobStores.fileJobStore: Path to job store directory is \'/work/jobstore\'.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,070 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: \'0c1289e1-e4df-469c-af8e-7eef101a9b82\'\nSearch path is [\'/work/data_for_job_36/exomeseq.cwl#main\', \'/root/.local/share/commonwl/data_for_job_36/exomeseq.cwl#main\', \'/usr/local/share/commonwl/data_for_job_36/exomeseq.cwl#main\', \'/usr/share/commonwl/data_for_job_36/exomeseq.cwl#main\']\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,072 MainThread DEBUG cwltool: Search path is [\'/work/data_for_job_36/exomeseq.cwl#main\', \'/root/.local/share/commonwl/data_for_job_36/exomeseq.cwl#main\', \'/usr/local/share/commonwl/data_for_job_36/exomeseq.cwl#main\', \'/usr/share/commonwl/data_for_job_36/exomeseq.cwl#main\']\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,075 MainThread DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): dockstore.org\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,389 MainThread DEBUG urllib3.connectionpool: https://dockstore.org:8443 "HEAD /api/ga4gh/v1/tools/data_for_job_36%2Fexomeseq.cwl%23main/versions/latest/plain-CWL/descriptor HTTP/1.1" 400 0\nResolved \'data_for_job_36/exomeseq.cwl#main\' to \'file:///work/data_for_job_36/exomeseq.cwl#main\'\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:35,390 MainThread INFO cwltool: Resolved \'data_for_job_36/exomeseq.cwl#main\' to \'file:///work/data_for_job_36/exomeseq.cwl#main\'\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,037 MainThread DEBUG cachecontrol.controller: Looking up "https://schema.org/docs/schema_org_rdfa.html" in the cache\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,038 MainThread DEBUG cachecontrol.controller: No cache entry available\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,039 MainThread DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): schema.org\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,206 MainThread DEBUG urllib3.connectionpool: https://schema.org:443 "GET /docs/schema_org_rdfa.html HTTP/1.1" 200 None\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,345 MainThread DEBUG cachecontrol.controller: Updating cache with response from "https://schema.org/docs/schema_org_rdfa.html"\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,345 MainThread DEBUG cachecontrol.controller: Caching due to etag\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,404 MainThread WARNING rdflib.term: https://schema.org/docs/!DOCTYPE html does not look like a valid URI, trying to serialize this will break.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,404 MainThread WARNING rdflib.term: https://schema.org/docs/html lang="en" does not look like a valid URI, trying to serialize this will break.\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:37,774 MainThread INFO rdflib.plugins.parsers.pyRdfa: Current options:\n\t\tpreserve space                         : True\n\t\toutput processor graph                 : True\n\t\toutput default graph                   : True\n\t\thost language                          : RDFa Core\n\t\taccept embedded RDF                    : False\n\t\tcheck rdfa lite                        : False\n\t\tcache vocabulary graphs                : False\n\t\t\ndata_for_job_36/exomeseq.cwl:4288:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:50,377 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4288:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4288:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:51,593 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4288:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4378:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:53,883 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4378:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3819:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:57,698 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3819:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3826:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:57,698 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3826:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4480:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:30:58,862 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4480:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3988:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:00,017 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3988:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:1498:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:01,284 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:1498:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3083:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:02,432 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3083:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4595:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:03,616 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4595:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4678:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:04,903 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4678:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:4685:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:04,903 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:4685:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:2255:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:06,059 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:2255:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nWorkflow checker warning:\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:06,074 MainThread WARNING cwltool: Workflow checker warning:\ndata_for_job_36/exomeseq.cwl:211:21: Source \'threads\' of type ["null", "int"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:435:25:   with sink \'threads\' of type "int"\ndata_for_job_36/exomeseq.cwl:644:25: Source \'output_HaplotypesBam\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:228:21:   with sink \'haplotypes_bam\' of type "File"\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:06,074 MainThread WARNING cwltool: data_for_job_36/exomeseq.cwl:211:21: Source \'threads\' of type ["null", "int"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:435:25:   with sink \'threads\' of type "int"\ndata_for_job_36/exomeseq.cwl:644:25: Source \'output_HaplotypesBam\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:228:21:   with sink \'haplotypes_bam\' of type "File"\ndata_for_job_36/exomeseq.cwl:1327:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:08,514 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:1327:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:1327:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:09,654 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:1327:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:1909:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:14,607 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:1909:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3325:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:15,744 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3325:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\ndata_for_job_36/exomeseq.cwl:3559:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:16,888 MainThread WARNING salad: data_for_job_36/exomeseq.cwl:3559:29: unrecognized extension field `https://schema.org/citation`.  Did you include a $schemas section?\nWorkflow checker warning:\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:16,897 MainThread WARNING cwltool: Workflow checker warning:\ndata_for_job_36/exomeseq.cwl:1043:25: Source \'vqsr_rscript\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:741:21:   with sink \'variant_recalibration_snps_indels_rscript\' of type "File"\ndata_for_job_36/exomeseq.cwl:1102:25: Source \'vqsr_rscript\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:765:21:   with sink \'variant_recalibration_snps_rscript\' of type "File"\nvm-job36-5b5a6c41-b939-43c3-a24b-8b456e7ddefd 2018-08-18 17:31:16,897 MainThread WARNING cwltool: data_for_job_36/exomeseq.cwl:1043:25: Source \'vqsr_rscript\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:741:21:   with sink \'variant_recalibration_snps_indels_rscript\' of type "File"\ndata_for_job_36/exomeseq.cwl:1102:25: Source \'vqsr_rscript\' of type ["null", "File"] is partially incompatible\ndata_for_job_36/exomeseq.cwl:765:21:   with sink \'variant_recalibration_snps_rscript\' of type "File"\nTraceback (most recent call last):\n  File "/usr/local/bin/cwltoil", line 11, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 883, in main\n    fillInDefaults(t.tool["inputs"], job)\n  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 400, in fillInDefaults\n    raise WorkflowException("Missing required input parameter `%s`" % shortname(inp["id"]))\n  File "/usr/local/lib/python2.7/dist-packages/schema_salad/sourceline.py", line 157, in __exit__\n    raise self.makeError(six.text_type(exc_value))\ncwltool.errors.WorkflowException: data_for_job_36/exomeseq.cwl:4804:17: Missing required input parameter `read_pairs`'
```

Missing required input parameter `read_pairs`.

I walked through creating a job with a simple pair of files, and `read_pairs` isn't present in the `job_order` json after creating the job. See jobs 36 (client) and 37 (mine).

This may be a server-side or imported workflow issue, but I figured we'd start here.

Haven't tested CLI behavior.

**Comment by dleehr** [comment]
Job 36 (created on 2018-07-19) is not missing the read_pairs variable

**Comment by dleehr** [comment]
Issue is happening before the job gets created. The job-answer-set for the two recent jobs is missing the `read_pairs`, but the answer set for job 36 has it.

**Comment by dleehr** [comment]
bespin-dev has the same behavior

**Comment by dleehr** [comment]
I confirmed in local testing. Reverting #126 fixes this issue
